language: node_js
# 4.3.2 and 6.10.3 are what AWS Lambda currently uses
node_js:
  - "6.10.3"
  - "5"
  - "4.3.2"

before_install: if [[ `npm -v` != 5* ]]; then npm i -g npm@5; fi

script:
   - grunt standards
   - npm test

# For code coverage:
after_success:
   cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
